# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-69fc73cd-71c1-4ad7-ba38-d346ca04394f";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-69fc73cd-71c1-4ad7-ba38-d346ca04394f".device = "/dev/disk/by-uuid/69fc73cd-71c1-4ad7-ba38-d346ca04394f";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-69fc73cd-71c1-4ad7-ba38-d346ca04394f";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-69fc73cd-71c1-4ad7-ba38-d346ca04394f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/95BC-5D8B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-db0dc968-2e6b-47b7-815e-82b4f2211ca7"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
